Repository Xeroxxx/tplink-energy-monitor, pull requests merged in 2020-09, with the labels that each got.

#12 Feature/settings view
  src/public/javascripts/dash.js
  src/public/stylesheets/style.css
  src/routes/index.js
  src/services/device-manager.js
  src/views/home.hbs
  src/views/partials/common/button.hbs
  src/views/partials/common/currencyInput.hbs
  src/views/partials/common/panel.hbs
  src/views/partials/includes/home/footer.hbs
  src/views/partials/includes/home/header.hbs
  src/views/partials/includes/home/index.hbs
  src/views/partials/includes/navbar.hbs
  src/views/partials/includes/settings/footer.hbs
  src/views/partials/includes/settings/header.hbs
  src/views/partials/includes/settings/index.hbs
  src/views/settings.hbs
Labels: enhancement

#16 Update README.md
  README.md
Labels: documentation

#21 Fixed pointablility of PlugState
  src/public/javascripts/dash.js
Labels: bug
